[package]
name = "snowbox"
version = "0.0.0"
edition.workspace = true
license.workspace = true
description = "Host Daemon for Snowbox"

[[bin]]
name = "snowbox"
path = "src/main.rs"

[dependencies]
anyhow = "1"
axum = { version = "0.8", features = ["ws"] }
constant_time_eq = "0.4"
dirs = "6"
hex = "0.4"
nix-bindings-expr = { git = "https://github.com/nixops4/nix-bindings-rust" }
nix-bindings-flake = { git = "https://github.com/nixops4/nix-bindings-rust" }
nix-bindings-store = { git = "https://github.com/nixops4/nix-bindings-rust" }
nix-bindings-util = { git = "https://github.com/nixops4/nix-bindings-rust" }
rand = "0.9"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tar = "0.4"
tokio = { version = "1", features = ["macros", "rt-multi-thread", "net", "io-util", "time", "signal"] }
tower-http = { version = "0.6", features = ["fs"] }
uuid = { version = "1", features = ["v4", "serde"] }

[target.'cfg(target_os = "macos")'.dependencies]
block2 = "0.6"
dispatch2 = "0.3"
libc = "0.2"
objc2 = "0.6"
objc2-foundation = "0.3"
objc2-virtualization = "0.3"

[target.'cfg(target_os = "linux")'.dependencies]
libc = "0.2"

[dev-dependencies]
http-body-util = "0.1"
tempfile = "3"
tower = { version = "0.5", features = ["util"] }
